[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Sepolia network configuration
[rpc_endpoints]
sepolia = "wss://ethereum-sepolia-rpc.publicnode.com"

# Sepolia chain configuration
[profile.chains]
sepolia = 11155111

# Etherscan API keys for contract verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Verification settings
[profile.default.verifier]
etherscan = { key = "${ETHERSCAN_API_KEY}" }
