[profile.default]
src = "packages/foundry/src"
out = "packages/foundry/out"
libs = ["node_modules", "lib", "packages/foundry/lib"]
remappings = [
    "@flarenetwork/flare-periphery-contracts/=node_modules/@flarenetwork/flare-periphery-contracts/"
]
test = "packages/foundry/test"
eth_rpc_url = "https://coston2-api.flare.network/ext/C/rpc" # Default to Flare Testnet (Coston2)
fork_url = "https://coston2-api.flare.network/ext/C/rpc" # Default tests to Flare testnet
cbor_metadata = true
evm_version = "paris" # Avoid PUSH0 (EIP-3855) on chains that don’t support Shanghai

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# RPC endpoints
[rpc_endpoints]
# Tenderly Virtual Mainnet
# Public Explorer: https://dashboard.tenderly.co/explorer/vnet/12d3291a-a185-4890-a48a-dd152c871633/transactions
mainnet_tenderly_http = "https://virtual.mainnet.us-east.rpc.tenderly.co/420b1805-6a91-4b32-b1c2-d37896a360cb"
mainnet_tenderly_wss = "wss://virtual.mainnet.us-east.rpc.tenderly.co/4996bd0e-fa2d-451e-961d-41fad07d2baf"

# Sepolia (kept for reference)
sepolia = "wss://ethereum-sepolia-rpc.publicnode.com"

# Flare Testnet (Coston2)
coston2 = "https://coston2-api.flare.network/ext/C/rpc"

# Katana Mainnet
katana = "https://rpc.katana.network"

[profile.chains]
mainnet = 1
sepolia = 11155111
coston2 = 114

# Etherscan API keys for contract verification
[etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${TENDERLY_ACCESS_KEY}", chain = 1, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# Flare Coston2 explorer is Blockscout-style; Foundry verifies via blockscout   
coston2 = { key = "unused", url = "https://coston2-explorer.flare.network/api" }
katana = { key = "${ETHERSCAN_API_KEY}", url = "https://api.katanascan.com/api" }

# Verification settings
[profile.default.verifier]
etherscan = { key = "${ETHERSCAN_API_KEY}" }
